// examples/angular-counter-example/src/app/components/counter.component.ts
import { Component, OnInit, OnDestroy, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AgentBridgeService } from '../services/agent-bridge.service';
import { z } from 'zod';

/**
 * Counter Component
 * A counter that can be controlled by AI agents via AgentBridge
 */
@Component({
  selector: 'app-counter',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="counter-container">
      <div class="counter-card">
        <h2>AgentBridge Counter</h2>
        <p class="subtitle">Controlled by AI Agents</p>
        
        <div class="counter-display">
          <div class="count-value">{{ count() }}</div>
          <div class="count-label">Current Count</div>
        </div>
        
        <div class="button-group">
          <button 
            class="btn btn-decrement" 
            (click)="decrement()"
            [disabled]="!isConnected()">
            <span class="btn-icon">−</span>
            Decrement
          </button>
          
          <button 
            class="btn btn-reset" 
            (click)="reset()"
            [disabled]="!isConnected()">
            <span class="btn-icon">↻</span>
            Reset
          </button>
          
          <button 
            class="btn btn-increment" 
            (click)="increment()"
            [disabled]="!isConnected()">
            <span class="btn-icon">+</span>
            Increment
          </button>
        </div>
        
        <div class="info-section">
          <div class="info-item">
            <span class="info-label">Component ID:</span>
            <code>main-counter</code>
          </div>
          <div class="info-item">
            <span class="info-label">Actions:</span>
            <code>increment, decrement, reset, setTo</code>
          </div>
          <div class="info-item">
            <span class="info-label">State:</span>
            <code>{{ stateJson() }}</code>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrl: './counter.component.css'
})
export class CounterComponent implements OnInit, OnDestroy {
  // Signals for reactive state
  count = signal(0);
  isConnected = computed(() => this.agentBridge.connectionStatus() === 'connected');
  stateJson = computed(() => JSON.stringify({ count: this.count() }));
  
  constructor(private agentBridge: AgentBridgeService) {}
  
  ngOnInit(): void {
    // Register this counter component with AgentBridge
    this.registerWithAgentBridge();
  }
  
  ngOnDestroy(): void {
    // Unregister when component is destroyed
    this.agentBridge.unregisterComponent('main-counter');
  }
  
  /**
   * Register this component with AgentBridge
   */
  private registerWithAgentBridge(): void {
    this.agentBridge.registerComponent(
      'main-counter',
      'A counter that can be incremented, decremented, or reset',
      'counter',
      {
        properties: z.object({
          count: z.number().describe('Current count value')
        }),
        actions: {
          increment: {
            description: 'Increment the counter by 1',
            parameters: z.object({}),
            handler: async () => {
              this.increment();
              return { success: true, count: this.count() };
            }
          },
          decrement: {
            description: 'Decrement the counter by 1',
            parameters: z.object({}),
            handler: async () => {
              this.decrement();
              return { success: true, count: this.count() };
            }
          },
          reset: {
            description: 'Reset the counter to zero',
            parameters: z.object({}),
            handler: async () => {
              this.reset();
              return { success: true, count: this.count() };
            }
          },
          setTo: {
            description: 'Set the counter to a specific value',
            parameters: z.object({
              value: z.number().describe('The value to set')
            }),
            handler: async (params: { value: number }) => {
              this.setTo(params.value);
              return { success: true, count: this.count() };
            }
          }
        },
        authLevel: 'public',
        tags: ['counter', 'ui', 'interactive']
      }
    );
  }
  
  /**
   * Increment the counter
   */
  increment(): void {
    this.count.update(c => c + 1);
    console.log(`➕ Counter incremented to ${this.count()}`);
  }
  
  /**
   * Decrement the counter
   */
  decrement(): void {
    this.count.update(c => c - 1);
    console.log(`➖ Counter decremented to ${this.count()}`);
  }
  
  /**
   * Reset the counter to zero
   */
  reset(): void {
    this.count.set(0);
    console.log(`↻ Counter reset to 0`);
  }
  
  /**
   * Set the counter to a specific value
   */
  setTo(value: number): void {
    this.count.set(value);
    console.log(`🎯 Counter set to ${value}`);
  }
}

// examples/react-counter/src/components/Counter.js
import React, { useState, useCallback } from 'react';
import { useRegisterComponent } from '@agentbridge/react';
import './Counter.css';

function Counter({ onCountChange }) {
  const [count, setCount] = useState(0);
  
  // Callback functions for the counter
  const increment = useCallback(() => {
    setCount(prevCount => {
      const newCount = prevCount + 1;
      onCountChange && onCountChange('Incremented', newCount);
      return newCount;
    });
  }, [onCountChange]);
  
  const decrement = useCallback(() => {
    setCount(prevCount => {
      const newCount = prevCount - 1;
      onCountChange && onCountChange('Decremented', newCount);
      return newCount;
    });
  }, [onCountChange]);
  
  const reset = useCallback(() => {
    setCount(0);
    onCountChange && onCountChange('Reset', 0);
  }, [onCountChange]);
  
  // Register the counter component for AI control
  useRegisterComponent({
    // Unique identifier for this component
    id: 'main-counter',
    
    // Type of component
    type: 'counter',
    
    // Display name for the component
    name: 'Main Counter',
    
    // Description of what this component does
    description: 'A counter that can be incremented, decremented, or reset',
    
    // Current properties/state of the component
    properties: {
      count: count,
      isPositive: count >= 0,
      isEven: count % 2 === 0
    },
    
    // Actions that can be performed on this component
    actions: {
      increment: {
        description: 'Increase the counter by 1',
        handler: increment
      },
      decrement: {
        description: 'Decrease the counter by 1',
        handler: decrement
      },
      reset: {
        description: 'Reset the counter to 0',
        handler: reset
      },
      setTo: {
        description: 'Set the counter to a specific value',
        parameters: {
          type: 'object',
          properties: {
            value: { 
              type: 'number', 
              description: 'The value to set the counter to' 
            }
          },
          required: ['value']
        },
        handler: ({ value }) => {
          setCount(value);
          onCountChange && onCountChange('Set to', value);
        }
      }
    }
  });
  
  return (
    <div className="counter">
      <h2>Counter</h2>
      <div className="counter-value">
        <span className={count >= 0 ? 'positive' : 'negative'}>
          {count}
        </span>
      </div>
      <div className="counter-info">
        <p>The count is {count % 2 === 0 ? 'even' : 'odd'}</p>
        <p>The count is {count >= 0 ? 'positive' : 'negative'}</p>
      </div>
      <div className="counter-controls">
        <button onClick={decrement}>-</button>
        <button onClick={reset}>Reset</button>
        <button onClick={increment}>+</button>
      </div>
      <div className="counter-help">
        <p>This counter is registered with AgentBridge and can be controlled by AI agents.</p>
        <p>Try these commands:</p>
        <ul>
          <li>Increment the counter</li>
          <li>Decrement the counter</li>
          <li>Reset the counter</li>
          <li>Set the counter to 10</li>
        </ul>
      </div>
    </div>
  );
}

export default Counter;
