// examples/simple-counter-example/src/components/Counter.tsx
import React, { useState, useCallback } from 'react';
import { useAgentComponent, AgentButton } from '@agentbridge/react';
import './Counter.css';

interface CounterState {
  count: number;
}

function Counter() {
  const [count, setCount] = useState(0);
  
  // Callback functions for the counter
  const increment = useCallback(() => {
    setCount(prevCount => prevCount + 1);
  }, []);
  
  const decrement = useCallback(() => {
    setCount(prevCount => prevCount - 1);
  }, []);
  
  const reset = useCallback(() => {
    setCount(0);
  }, []);
  
  // Register the counter component with AgentBridge
  const counterComponent = useAgentComponent<{}, CounterState>({
    componentId: 'main-counter',
    componentType: 'counter',
    description: 'A counter that can be incremented, decremented, or reset',
    initialState: { count: 0 },
    properties: {
      count: count,
      isPositive: count >= 0,
      isEven: count % 2 === 0
    },
    actions: {
      increment: {
        description: 'Increase the counter by 1',
        parameters: { type: 'object', properties: {} },
        handler: async () => {
          let newCount: number;
          setCount(prevCount => {
            newCount = prevCount + 1;
            return newCount;
          });
          return { success: true, newCount: newCount! };
        }
      },
      decrement: {
        description: 'Decrease the counter by 1',
        parameters: { type: 'object', properties: {} },
        handler: async () => {
          let newCount: number;
          setCount(prevCount => {
            newCount = prevCount - 1;
            return newCount;
          });
          return { success: true, newCount: newCount! };
        }
      },
      reset: {
        description: 'Reset the counter to 0',
        parameters: { type: 'object', properties: {} },
        handler: async () => {
          setCount(0);
          return { success: true, newCount: 0 };
        }
      },
      setTo: {
        description: 'Set the counter to a specific value',
        parameters: {
          type: 'object',
          properties: {
            value: { 
              type: 'number', 
              description: 'The value to set the counter to' 
            }
          },
          required: ['value']
        },
        handler: async (params: { value: number }) => {
          setCount(params.value);
          return { success: true, newCount: params.value };
        }
      }
    },
    onStateChange: (updates) => {
      // Update local state when agent changes it
      if (updates.count !== undefined) {
        setCount(updates.count);
      }
    }
  });
  
  // No need to manually sync count - React manages the state
  // The agent can read the current state through the action handlers
  
  return (
    <div className="counter">
      <h2>Counter</h2>
      <div className="counter-value">
        <span className={count >= 0 ? 'positive' : 'negative'}>
          {count}
        </span>
      </div>
      <div className="counter-info">
        <p>The count is <strong>{count % 2 === 0 ? 'even' : 'odd'}</strong></p>
        <p>The count is <strong>{count >= 0 ? 'positive' : 'negative'}</strong></p>
      </div>
      <div className="counter-controls">
        <AgentButton
          componentId="decrement-button"
          label="-"
          description="Decrement the counter"
          onClick={decrement}
          variant="secondary"
        />
        <AgentButton
          componentId="reset-button"
          label="Reset"
          description="Reset the counter to zero"
          onClick={reset}
          variant="outline"
        />
        <AgentButton
          componentId="increment-button"
          label="+"
          description="Increment the counter"
          onClick={increment}
          variant="primary"
        />
      </div>
      <div className="counter-help">
        <p>This counter is registered with AgentBridge and can be controlled by AI agents.</p>
        <p>Try these commands:</p>
        <ul>
          <li>Increment the counter</li>
          <li>Decrement the counter</li>
          <li>Reset the counter</li>
          <li>Set the counter to 10</li>
        </ul>
      </div>
    </div>
  );
}

export default Counter;

// examples/angular-counter-example/src/app/components/counter.component.ts
import { Component, OnInit, OnDestroy, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AgentBridgeService } from '../services/agent-bridge.service';
import { z } from 'zod';

/**
 * Counter Component
 * A counter that can be controlled by AI agents via AgentBridge
 */
@Component({
  selector: 'app-counter',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="counter-container">
      <div class="counter-card">
        <h2>AgentBridge Counter</h2>
        <p class="subtitle">Controlled by AI Agents</p>
        
        <div class="counter-display">
          <div class="count-value">{{ count() }}</div>
          <div class="count-label">Current Count</div>
        </div>
        
        <div class="button-group">
          <button 
            class="btn btn-decrement" 
            (click)="decrement()"
            [disabled]="!isConnected()">
            <span class="btn-icon">−</span>
            Decrement
          </button>
          
          <button 
            class="btn btn-reset" 
            (click)="reset()"
            [disabled]="!isConnected()">
            <span class="btn-icon">↻</span>
            Reset
          </button>
          
          <button 
            class="btn btn-increment" 
            (click)="increment()"
            [disabled]="!isConnected()">
            <span class="btn-icon">+</span>
            Increment
          </button>
        </div>
        
        <div class="info-section">
          <div class="info-item">
            <span class="info-label">Component ID:</span>
            <code>main-counter</code>
          </div>
          <div class="info-item">
            <span class="info-label">Actions:</span>
            <code>increment, decrement, reset, setTo</code>
          </div>
          <div class="info-item">
            <span class="info-label">State:</span>
            <code>{{ stateJson() }}</code>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrl: './counter.component.css'
})
export class CounterComponent implements OnInit, OnDestroy {
  // Signals for reactive state
  count = signal(0);
  isConnected = computed(() => this.agentBridge.connectionStatus() === 'connected');
  stateJson = computed(() => JSON.stringify({ count: this.count() }));
  
  constructor(private agentBridge: AgentBridgeService) {}
  
  ngOnInit(): void {
    // Register this counter component with AgentBridge
    this.registerWithAgentBridge();
  }
  
  ngOnDestroy(): void {
    // Unregister when component is destroyed
    this.agentBridge.unregisterComponent('main-counter');
  }
  
  /**
   * Register this component with AgentBridge
   */
  private registerWithAgentBridge(): void {
    this.agentBridge.registerComponent(
      'main-counter',
      'A counter that can be incremented, decremented, or reset',
      'counter',
      {
        properties: z.object({
          count: z.number().describe('Current count value')
        }),
        actions: {
          increment: {
            description: 'Increment the counter by 1',
            parameters: z.object({}),
            handler: async () => {
              this.increment();
              return { success: true, count: this.count() };
            }
          },
          decrement: {
            description: 'Decrement the counter by 1',
            parameters: z.object({}),
            handler: async () => {
              this.decrement();
              return { success: true, count: this.count() };
            }
          },
          reset: {
            description: 'Reset the counter to zero',
            parameters: z.object({}),
            handler: async () => {
              this.reset();
              return { success: true, count: this.count() };
            }
          },
          setTo: {
            description: 'Set the counter to a specific value',
            parameters: z.object({
              value: z.number().describe('The value to set')
            }),
            handler: async (params: { value: number }) => {
              this.setTo(params.value);
              return { success: true, count: this.count() };
            }
          }
        },
        authLevel: 'public',
        tags: ['counter', 'ui', 'interactive']
      }
    );
  }
  
  /**
   * Increment the counter
   */
  increment(): void {
    this.count.update(c => c + 1);
    console.log(`➕ Counter incremented to ${this.count()}`);
  }
  
  /**
   * Decrement the counter
   */
  decrement(): void {
    this.count.update(c => c - 1);
    console.log(`➖ Counter decremented to ${this.count()}`);
  }
  
  /**
   * Reset the counter to zero
   */
  reset(): void {
    this.count.set(0);
    console.log(`↻ Counter reset to 0`);
  }
  
  /**
   * Set the counter to a specific value
   */
  setTo(value: number): void {
    this.count.set(value);
    console.log(`🎯 Counter set to ${value}`);
  }
}
